server:
  port: 8024
spring:
  application:
    name: hms-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/crizefish/config-repo	# \u914d\u7f6egit\u4ed3\u5e93\u7684\u5730\u5740
          search-paths: config-repo	# git\u4ed3\u5e93\u5730\u5740\u4e0b\u7684\u76f8\u5bf9\u5730\u5740\uff0c\u53ef\u4ee5\u914d\u7f6e\u591a\u4e2a\uff0c\u7528,\u5206\u5272\u3002
          username: crizefish	# git\u4ed3\u5e93\u7684\u8d26\u53f7
          password: xqy1020	# git\u4ed3\u5e93\u7684\u5bc6\u7801
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8025/eureka/

          
