server:
  port: 8024
          
spring:
  application:
    name: hms-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/crizefish/config-repo
          search-paths: config-repo
          username: crizefish
          password: xqy1020
          
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8025/eureka/

          
